# Plugins
plugins:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']

# Site Settings
title: "Monash Science Symposium 2021"
email: "monash.sciencesymposium@gmail.com"
description: "Monash Science Symposium (MSS) 2021. It is a student-led event by the School of Science postgraduate students of Monash University Malaysia (MUM)."
baseurl: "/website-2021"
url: "https://monash-sciencesymposium.github.io"
#googleAnalyticsTrackingId: "UA-181963946-1"
#googleAnalyticsSiteUrl: "monash-sciencesymposium.com"
#siteVerification: "htLClk4VKGu4DxmQigKnQQfLpjcDlpQ0whEJXEdchGE"

# Organizer Info
organizerName: "MSS"
organizerAlternateName: "Monash Science Symposium"
organizerDescription: "<em>Symbiosis: Exploring Extraordinary Possibilities</em>"
organizerEmail: "monash.sciencesymposium@gmail.com"
organizerLogo: "/img/seo/organizer-logo.png"
organizerLink: "monash-sciencesymposium.com"

# Head
metaKeywords: "mss, monash, science, symposium, malaysia, 2021"
twitterAccount: "@mss_mum"
socialImageSrcGooglePlus: "/img/seo/organizer-logo.png"
socialImageSrcTwitter: "/img/seo/organizer-logo.png"
socialImageSrcFacebook: "/img/seo/organizer-logo.png"

# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {permalink: "/about-us/", text: "About Us"}
 - {permalink: "/speakers", text: "Speakers"}
bottomNavigationLinks:
# - {link: "https://forms.gle/VXkd4uHN3hi81jvi7", text: "Register here"}
rightNavigationButtons:
# - {link: "https://forms.gle/VXkd4uHN3hi81jvi7", text: "Register here"}

# Miscellaneous links
speakerButtonRegister: "https://forms.gle/VXkd4uHN3hi81jvi7"

# Hero Block
heroImage: "hero.jpg"
heroTitle: "Monash Science Symposium (MSS) <typeout>"
#eventDate: "3<sup>rd</sup> - 5<sup>th</sup> February 2021"
heroMotto: "<em>Symbiosis: Exploring Extraordinary Possibilities</em>"
typeoutTextValues: '"", "2021" '
typeoutFallback: ""
heroButtons:
#- {link: "https://forms.gle/VXkd4uHN3hi81jvi7", text: "Register here"}

#Mini Science Series Block
miniSeries1: "Because of the COVID-19 pandemic, we unfortunately had to cancel the symposium we had planned for 2021. In lieu of the symposium, we decided to conduct a the Mini Science Series, a series of webinars that were held over Zoom. Below are the posters for the three webinars we conducted: <ol>Pandemic Preparedness: Challenges Faced and Lessons Learnt</ol><ol>Am I OK? Adapting to the New Norm During a Pandemic</ol><ol>Digital Health: A Step Towards Modernized Healthcare</ol>"
miniSeriesPoster:
 - {image: "poster-1.jpg"}
 - {image: "poster-2.jpg"}
 - {image: "poster-3.jpg"}
miniSeriesButtons:
 - {permalink: "/mini-science-series", text: "Learn about the speakers"}

#Key Dates Block
keyDatesBlockImage: "key-dates.jpg"
keyDates:
 - {date: "3 Jan 2019", text: "Deadline for something pretty important"}
 - {date: "7 Jan 2019", text: "Registration does not close"}
 - {date: "10 Jan 2019", text: "Early bird tickets"}

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "15", specialCharacter: " Jan", info: "2020", detail: "Early Bird Deadline"}
 - {count: "30", specialCharacter: " Jan", info: "2020", detail: "Abstract Deadline"}
 - {count: "1", specialCharacter: " Feb", info: "2020", detail: "Registration Closes"}

# Latest News Block
latestNewsTitle: "Latest news"

# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 4
rockstarSpeakersTitle: "Rockstar speakers"
rockstarSpeakersButtonText: "See all speakers"

# Location Block
locationBlockTitle: "Location"
eventLocationName: "Monash University Malaysia"
#eventLocationLink: "http://cabinet.kinopalace.lviv.ua/showtimes/"
eventStreetAddress: "Jalan Lagoon Selatan, Bandar Sunway"
eventAddressLocality: "47500 Subang Jaya, Selangor, Malaysia"
#eventAddressLocalityRegion: "Lv{% include about.html %}ivska"
eventPostalCode: "47500"
eventAddressCountry: "Malaysia"
eventStartTime: "8 Jan (09:00)"
#eventDoorTime: "09:00"
eventEndTime: "10 Jan (20:00)"
eventPlaceCoordinates: "3.064917, 101.600973"
mapCenterCoordinates: "3.064917, 101.600973"
mapMobileCenterCoordinates: "3.064917, 101.600973"

# Venue Block
venueBlockTitle: "Venue"
venueBigImage: "venue_0.jpg"
venueSmallImage1: "venue_1.jpg"
venueSmallImage2: "venue_2.jpg"
venueSmallImage3: "venue_3.jpg"
venueTitle: "Kinopalace Cinema"
venueFeatures: ["3 huge cinema screens", "Doulby Digital Surround EX audio system", "Located directly in the city center"]

# Tweets Feed Block
tweetsFeedImage: "twitter-feed.jpg"
tweetsFeedTitle: "What's Up?"
twitterHashTag: "devfest"
twitterFeed: "http://lviv.gdg.org.ua/tweetledee/favoritesjson.php?c=10&cache_interval=8000"

# Partners Block
partnersTitle: "Sponsors"
partnersDescription: "We would like to thank our sponsors for..."
partnersSponsorsButton: "Become a sponsor"

# Subscribe Block
subscribeImage: "subscribe.jpg"
subscribeTitle: "Subscribe for updates"
subscribeAction: "https://gdg.us5.list-manage1.com/subscribe/post?u=9fc8aa205b0521b5f05fc8e1e&amp;id=ae0fb459fc"
subscribeInfo: "Registration will be open around end of August. Number of tickets are limited. Stay tuned!"

# About MSS Block
aboutMSSBlockTitle: "About MSS"
aboutMSS: "The Monash Science Symposium (MSS) is a student-led event by the School of Science postgraduate students of Monash University Malaysia (MUM). We hope to initiate the conference as an annual event that acts as a platform for students to gain experience and valuable insight towards their research. It also serves as a promotional event to highlight the capabilities of postgraduates in research outputs and the dissemination of their scientific findings to a broader, and ideally, international audience. It is also can be the future direction of this event will aim to showcase research here in Monash to engage with other universities and industries to increase the networking opportunities."
objectives:
  - {objective: "Provide a platform for researchers from around the world to exchange ideas, establish collaborations and have meaningful discussions on current scientific issues​."}
  - {objective: "Allow the establishment of professional relations with other sectors (industries, research institutes and non-academia)."}
  - {objective: "Increase the number of local and international participants​."}
  - {objective: "Establish a more significant relation with government institutes and industries."}

# Team Block
teamBlockTitle: "Meet the Team"

# History Block
history1: "MSS was first held in 2013 as a gathering of local science graduate research students to share and discuss their research findings. Since then, it has grown in size and scope to include the student community of other local and international universities and research institutes. True to the Monash motto “<em>Ancora Imparo</em>”, the Symposium aims to enhance the science learning experience by encouraging knowledge exchange between researchers, promoting local research work, exploring potential collaborations, and fostering closer ties with other research universities."
history2: "In 2014, the Symposium has registered more than 150 student participants, half of which represent participants from 9 other different local universities/research institutes. In 2016, the symposium was held with more registered participants, including external participants who were from 13 universities and a government agency. A new scope was introduced in MSS 2016, covering a total of 6 major life sciences branches and were presented over 3-day periods. The Symposium had received overwhelming positive feedback from the participants. In 2018, an intervarsity symposium which served as a promotional event to highlight the capabilities of HDR students of Monash University Malaysia in producing quality research outputs and the dissemination of their scientific findings to a broader audience."
history3: "For MSS 2021, we intend to continue the legacy by making the event bigger as well as introduce a new science category, “Science Communication and Safety”. We also intend to encourage supervisors/lecturers to partake in MSS 2021 as the scientific committee which would assist in the abstract screening process.  We therefore propose for an intervarsity symposium to be held for the graduate research students, staff and company agencies."

# Footer
socialLinks:
  - {link: "https://twitter.com/mss_mum", icon: "twitter"}
  - {link: "https://linkedin.com/in/monash-science-symposium-790b301a1", icon: "linkedin"}
  - {link: "https://www.instagram.com/monash.sciencesymposium/", icon: "instagram"}
  - {link: "https://www.facebook.com/monashsciencesymposium/", icon: "facebook"}
footerBlocks:
 -
  title: "Contact"
  links:
   - {link: "mailto:mum-sciencesymposium@monash.edu", text: "Email us"}
 -
  title: "Past events"
  links:
    - {link: "https://monashscience2018.jimdofree.com/", text: "MSS 2018"}
    - {link: "https://monashscience.jimdofree.com/", text: "MSS 2016"}

# Blog
#blogTitle: "Latest news"
#blogCommentsEnabled: true
#discusShortName: "devfestua"

# Speakers List Block
showSessions: false

# Logistics Find Way Block
# findWayTitle: "Find your way here"
# findWayDistance: "Distance"
# findWayDriving: "DRIVING"
# findWayWalking: "WALKING"
# findWayBicycling: "BICYCLING"
# findWayTransit: "TRANSIT"
# findWayFindFlight: "Find Flight"
# logisticsMapCenterCoordinates: "49.056728, 3.117289"
# logisticsMapMobileCenterCoordinates: "48.335365, 23.711648"
# logisticsMapAutoDirections: false

# Logistics Direction Details Block
directionDetailsTitle: "Sunway City"
directionDetailsDescription: "Monash University Malaysia is located in Bandar Sunway (Sunway City), a township equipped with leisure, entertainment, educaiton and residential facilities. You can commute around Sunway City through a few options below:"
directionDetailsCards:
  -
    title: "Canopy Walk"
    information: "The canopy walk is an elevated and secure (monitored by close-circuit television cameras) walkway in Bandar Sunway that connects our campus to the Sunway Pyramid mall. The walk takes about 15-20 minutes. For more information, check out our <a href=\"https://drive.google.com/open?id=1DWHKEqD5RvDFFdRzlTYaCNNvKuY7ylkK&usp=sharing\">custom Google Map.</a>"
  -
    title: "BRT"
    information: "The game-changing Bus Rapid Transit (BRT) is Malaysia's first elevated Bus Rapid Transit system. This BRT Sunway line connects Sunway City with other public rail transportion (Setia Jaya KTM Komuter station and the USJ7 LRT station). Check out this <a href=\"https://www.malaysia-traveller.com/BRT-Sunway.html\">travel blog</a> for more information."
  -
    title: "Shuttle Bus"
    information: "The free Sunway Shuttble Bus service runs every 60 minutes (subject to traffic conditions). From Monday to Saturday, it operates from 7:00 AM - 10:15 PM. On Sundays, it's 9:00 AM - 10:15 PM. Please click <a href=\"https://drive.google.com/a/monash.edu/file/d/1qTRcUGG0i-Bhrq0HcJlEiFLqCrWQDa0Q/view?usp=sharing\">here for the list of bus stops.</a>"
  -
    title: "Grab"
    information: "Grab is one of Malaysia's most well-known ride-hailing services. Fares may vary depending on traffic and weather conditions. The Grab app is available on <a href=\"https://www.grab.com/my/download/\">App Store and Google Play.</a>"

# # Hackathon
# hackathonTitle: "Hackathon"
# enableHackathon: true

# # Hackathon Judges Block
# judgesImage: "judges.jpg"
# judgesTitle: "Judges"

# # Hackathon Prizes Block
# prizesTitle: "Prizes"
# prizes:
#  - {title: "2nd Place", image: "prize-2.png", info: "Amazing Moto 360"}
#  - {title: "1nd Place", image: "prize-1.png", info: "Nexus 5 with pre-installed Android L"}
#  - {title: "3nd Place", image: "prize-3.png", info: "Useful Chromecast"}

# # Hackathon Location Block
# hackathonLocationBlockTitle: "Location"
# hackathonLocationName: "Communa"
# hackathonLocationLink: "http://communa.net.ua/"
# hackathonStreetAddress: "1 Halytska St"
# hackathonAddressLocality: "Lviv"
# hackathonAddressLocalityRegion: "Lvivska"
# hackathonPostalCode: "79000"
# hackathonAddressCountry: "Ukraine"
# hackathonTimeTitle: "Hack through"
# hackathonStartTime: "2014-10-24T10:00"
# hackathonDoorTime: "09:00"
# hackathonEndTime: "2014-10-25T00:00"
# viewOnMap: "View on Google Maps"
# hackathonPlaceCoordinates: "49.840999, 24.031144"
# hackathonMapCenterCoordinates: "49.840696, 24.028754"
# hackathonMapMobileCenterCoordinates: "49.841639, 24.031182"
